## Fields
# Time that these estimates are for
time timestamp
# Estimated position of RGV 1 in the local inertial frame
float64[3] rgv1_position
# Estimated velocity of RGV 1 in the local inertial frame
float64[3] rgv1_velocity
# Confidence associated with the RGV 1 estimation (0: low, 1: high)
float64 rgv1_confidence
# Estimated position of RGV 2 in the local inertial frame
float64[3] rgv2_position
# Estimated velocity of RGV 2 in the local inertial frame
float64[3] rgv2_velocity
# Confidence associated with the RGV 2 estimation (0: low, 1: high)
float64 rgv2_confidence